### PR TITLE
Fixing issue https://github.com/ansible-lockdown/UBUNTU22-CIS/issues/180

### PR DESCRIPTION
**Pull request by DianaMariaDDM**
**Overall Review of Changes:**
This is the solution provided for issue [180](https://github.com/ansible-lockdown/UBUNTU22-CIS/issues/180).
It uses the same ansible module as before, only that it adds another task that edits the necessary line right above the `password [success=1 default=ignore] pam_unix.so obscure yescrypt` line.

**Issue Fixes:**

- https://github.com/ansible-lockdown/UBUNTU22-CIS/issues/180

**Enhancements:**
None

**How has this been tested?:**
Tested on my local test environment.

### CODE REVIEW

**Comment by uk-bolly** [comment]
hi @DianaMariaDDM 

Thank you for updating all of your branches. If i could request that you do it again, this should enable this older PR to complete as well.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @DianaMariaDDM 

I have added a warning that PRs are stale if your branch is not upto date, You will see that we have seen this on a number of your PRs. Hoping this helps us to highlight issues so we can get these resolved.

Many thanks

uk-bolly

**Comment by DianaMariaDDM** [comment]
Thank you for letting me know!

I have re-updated my branches and I have also fixed some indentation issues on some PRs. Now all the checks have passed on all PRs, hope this helps!

**Review by uk-bolly — APPROVED** [review]
Great changes

**Review by uk-bolly — APPROVED** [review]

**Pull request merged**
