### PR TITLE
Fix inject_facts_as_vars

### PR DESCRIPTION
**Pull request by jovial**
**Overall Review of Changes:**

Fixes regression in using inject-facts-as-vars=false.

See: 
- https://docs.ansible.com/ansible/2.9/reference_appendices/config.html#inject-facts-as-vars
- https://github.com/ansible-lockdown/UBUNTU22-CIS/pull/132

**Issue Fixes:**
Please list (using linking) any open issues this PR addresses

**Enhancements:**
Please list any enhancements/features that are not open issue tickets

**How has this been tested?:**
Tested locally and have enabled testing of this in CI to prevent regressions.

### CODE REVIEW

**Review by uk-bolly — APPROVED** [review]
NIce catch and great change

**Comment by uk-bolly** [comment]
hi @jovial 

Thank you for this PR, Great catch and update, unfortunatley the change is not GPG signed so i am not able to merge this into the devel branch. If you can sign the commits happy to merge the PR.

Many thanks

uk-bolly

**Comment by jovial** [comment]
> hi @jovial
> 
> Thank you for this PR, Great catch and update, unfortunatley the change is not GPG signed so i am not able to merge this into the devel branch. If you can sign the commits happy to merge the PR.
> 
> Many thanks
> 
> uk-bolly

Thanks for taking a look. I think the issue was that I hadn't uploaded my GPG to github. I've now uploaded this and the commits are showing as verified in the UI. Let me know if I need to do anything else.

**Review by uk-bolly — APPROVED** [review]
good work

**Pull request merged**
